[general]

# Squid access log to monitor
access_log = /var/log/squid/access.log

# Malicious domain signatures
signature_file = signatures/cumi-domains.txt

# Cumi alert log
alert_log = logs/cumi.log

